services:
  - type: cron
    name: ad-spy-scraper
    runtime: python
    schedule: "@every 1h"  # ⏰ exécuter toutes les heures (tu peux changer en "@daily", etc)
    buildCommand: "pip install -r requirements.txt && playwright install"
    startCommand: "python main.py"
